const state = {
  plan: [],
  user: null,
  projects: [],
  assets: [],
  projectId: null,
  selectedAsset: null,
  assetElement: null,
  voiceAsset: null,
  current: {
    format: "Story",
    hook: "Your to-do list isn't the problem.",
    body: "The way you plan your attention is.",
    cta: "Try FocusFlow today →",
    color: "#d7ff39"
  },
  previewFrame: 0,
  previewTimer: null
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
let toastTimer;

function toast(message) {
  $("#toast").textContent = message;
  $("#toast").classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => $("#toast").classList.remove("show"), 3000);
}

async function api(url, options = {}) {
  const response = await fetch(url, {
    credentials: "same-origin",
    headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    ...options
  });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Request failed.");
  return result;
}

const templates = {
  Story: [
    "POV: You finally stopped {pain}",
    "I thought I needed more discipline. I needed {product}.",
    "The tiny change that gave {audience} their evenings back",
    "Nobody warned me success would feel this messy",
    "A day in the life after {result}",
    "The moment I realized busy was not productive",
    "My Sunday-night reset used to take three hours",
    "I almost quit before I changed this one thing",
    "What burnout taught me about better systems",
    "This is your sign to stop doing it the hard way"
  ],
  Educate: [
    "3 mistakes keeping {audience} stuck",
    "The 10-minute rule that changes your whole week",
    "Why your current system keeps failing you",
    "Try this before you add another task",
    "The difference between a plan and a wish",
    "How to protect your best two hours",
    "A simple framework for {result}",
    "The productivity advice I wish I ignored sooner",
    "Do this when everything feels urgent",
    "One question that clears your entire to-do list"
  ],
  Promote: [
    "Still {pain}? There is a better way.",
    "Meet {product}: your unfair advantage",
    "Your next great week starts here",
    "What if {result} felt easy?",
    "Built for {audience} who are done settling",
    "Less busywork. More work that matters.",
    "The tool your Monday has been waiting for",
    "Turn scattered ideas into a clear next move",
    "Finally, a smarter way to {result}",
    "You bring the ambition. {product} brings the plan."
  ]
};

function showView(name) {
  $$(".studio-view").forEach(v => v.classList.remove("active"));
  $$(".side-nav").forEach(v => v.classList.toggle("active", v.dataset.view === name));
  $(`#${name}View`).classList.add("active");
}

$$(".side-nav").forEach(button => button.addEventListener("click", () => {
  if (button.dataset.view === "calendar" && !state.plan.length) generatePlan();
  showView(button.dataset.view);
}));

$$(".choice").forEach(choice => {
  choice.addEventListener("click", () => setTimeout(() => choice.classList.toggle("selected", choice.querySelector("input").checked), 0));
});

function fill(template, values) {
  return template
    .replaceAll("{product}", values.product)
    .replaceAll("{audience}", values.audience)
    .replaceAll("{pain}", values.pain)
    .replaceAll("{result}", values.result);
}

async function generatePlan() {
  const description = $("#description").value.trim();
  const values = {
    product: $("#product").value.trim() || "Your product",
    audience: $("#audience").value.trim() || "your audience",
    result: description ? description.charAt(0).toLowerCase() + description.slice(1).replace(/\.$/, "") : "get better results",
    pain: "doing everything the hard way"
  };
  const submit = $("#briefForm button[type=submit]");
  submit.disabled = true;
  submit.firstChild.textContent = "Generating your content plan ";
  try {
    const result = await api("/api/generate", { method: "POST", body: JSON.stringify({
      product: values.product, audience: values.audience, description, goal: $("#goal").value
    }) });
    state.plan = result.ideas;
    $("#engineLabel").textContent = result.engine === "ollama" ? "LOCAL AI ACTIVE" : "OFFLINE ENGINE";
    $("#engineDescription").textContent = result.engine === "ollama" ? "Ideas generated by your private Ollama model." : "Private, zero-cost generation is ready.";
  } catch {
    const selected = $$(".choice input:checked").map(i => i.value);
    const formats = selected.length ? selected : ["Story", "Educate", "Promote"];
    const support = [
      "Catch the risk early, make the fix clear, and protect the final handoff.",
      "Turn a complicated review into a focused list of practical next steps.",
      "Document what was checked, what changed, and what still needs a person.",
      "Move review upstream so the team can fix issues before approvals stack up.",
      "Give every reviewer the same findings, priorities, and remaining risks.",
      "Find repeat problems across the whole project instead of one file at a time.",
      "Pair repeatable automated checks with visible, accountable human review.",
      "Replace last-minute guesswork with a consistent delivery-ready process.",
      "Explain the impact and the fix so feedback becomes action, not noise.",
      "Create a credible record of the work behind every confident delivery."
    ];
    const actions = ["See the workflow", "Save the checklist", "Start a private review", "Review before delivery", "Build your action plan", "Document the work", "Catch issues earlier", "Simplify the handoff", "Try the three-step method", `Explore ${values.product}`];
    state.plan = Array.from({length: 30}, (_, index) => {
      const format = formats[index % formats.length];
      const hook = fill(templates[format][Math.floor(index / formats.length) % templates[format].length], values);
      const cycle = Math.floor(index / support.length);
      const context = cycle === 1 ? ` Built for ${values.audience.split(",")[0]}.` : cycle === 2 ? ` Make it part of your next ${values.product} campaign.` : "";
      return {
        day: index + 1, format, hook,
        body: `${support[index % support.length]}${context}`,
        cta: actions[(index + cycle) % actions.length]
      };
    });
    toast("Using the built-in offline generator.");
  } finally {
    submit.disabled = false;
    submit.firstChild.textContent = "Generate my content plan ";
  }
  $("#planCount").textContent = "30";
  renderPlan();
}

$("#briefForm").addEventListener("submit", async event => {
  event.preventDefault();
  await generatePlan();
  showView("calendar");
});

function renderPlan(filter = "All") {
  const items = filter === "All" ? state.plan : state.plan.filter(item => item.format === filter);
  $("#calendarList").innerHTML = items.map((item, index) => `
    <article class="calendar-card" data-day="${item.day}">
      <span class="calendar-day">DAY ${String(item.day).padStart(2, "0")}</span>
      <span class="type-pill ${item.format}">${item.format.toUpperCase()}</span>
      <strong>${escapeHtml(item.hook)}</strong>
      <button aria-label="Edit clip">→</button>
    </article>`).join("");
  $$(".calendar-card").forEach(card => card.addEventListener("click", () => openEditor(state.plan.find(item => item.day === Number(card.dataset.day)))));
}

$$(".filter").forEach(button => button.addEventListener("click", () => {
  $$(".filter").forEach(b => b.classList.remove("active"));
  button.classList.add("active");
  renderPlan(button.dataset.filter);
}));

$("#newBrief").addEventListener("click", () => showView("brief"));
$("#backToPlan").addEventListener("click", () => showView("calendar"));

function openEditor(item) {
  state.current = {...item, color: item.format === "Story" ? "#ff725c" : item.format === "Educate" ? "#7095ff" : "#d7ff39"};
  $("#editFormat").value = state.current.format;
  $("#editHook").value = state.current.hook;
  $("#editBody").value = state.current.body;
  $("#editCta").value = state.current.cta;
  $("#editColor").value = state.current.color;
  updatePreview();
  showView("editor");
}

["editFormat", "editHook", "editBody", "editCta", "editColor"].forEach(id => {
  $(`#${id}`).addEventListener("input", () => {
    state.current = {
      format: $("#editFormat").value,
      hook: $("#editHook").value,
      body: $("#editBody").value,
      cta: $("#editCta").value,
      color: $("#editColor").value
    };
    updatePreview();
  });
});

const canvas = $("#previewCanvas");
const ctx = canvas.getContext("2d");

function roundedRect(context, x, y, w, h, r) {
  context.beginPath();
  context.roundRect(x, y, w, h, r);
  context.fill();
}

function wrapText(context, text, maxWidth) {
  const words = text.split(" ");
  const lines = [];
  let line = "";
  words.forEach(word => {
    const test = line ? `${line} ${word}` : word;
    if (context.measureText(test).width > maxWidth && line) {
      lines.push(line);
      line = word;
    } else line = test;
  });
  if (line) lines.push(line);
  return lines;
}

function fitTextBlock(context, text, maxWidth, maxLines, startSize, minSize, weight = 700) {
  let size = startSize;
  let lines = [];
  while (size >= minSize) {
    context.font = `${weight} ${size}px Manrope`;
    lines = wrapText(context, text, maxWidth);
    if (lines.length <= maxLines) return { lines, size };
    size -= 1;
  }
  context.font = `${weight} ${minSize}px Manrope`;
  lines = wrapText(context, text, maxWidth);
  const visible = lines.slice(0, maxLines);
  if (lines.length > maxLines) {
    let last = visible[maxLines - 1];
    while (last && context.measureText(`${last}…`).width > maxWidth) last = last.slice(0, -1).trim();
    visible[maxLines - 1] = `${last}…`;
  }
  return { lines: visible, size: minSize };
}

function drawTextBlock(context, block, x, y, lineHeight, color) {
  context.fillStyle = color;
  context.font = `700 ${block.size}px Manrope`;
  context.textAlign = "left";
  context.textBaseline = "top";
  block.lines.forEach((line, index) => context.fillText(line, x, y + index * lineHeight));
}

function fitSingleLine(context, text, maxWidth, startSize, minSize, weight = 800) {
  let size = startSize;
  while (size > minSize) {
    context.font = `${weight} ${size}px Manrope`;
    if (context.measureText(text).width <= maxWidth) break;
    size -= 1;
  }
  return size;
}

function drawFrame(progress = 0) {
  const { format, hook, body, cta, color } = state.current;
  ctx.fillStyle = "#11110f";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  if (state.assetElement) {
    const media = state.assetElement;
    const sourceWidth = media.videoWidth || media.naturalWidth || 360;
    const sourceHeight = media.videoHeight || media.naturalHeight || 640;
    const scale = Math.max(360 / sourceWidth, 640 / sourceHeight);
    const width = sourceWidth * scale;
    const height = sourceHeight * scale;
    ctx.globalAlpha = .48;
    ctx.drawImage(media, (360 - width) / 2, (640 - height) / 2, width, height);
    ctx.globalAlpha = 1;
    ctx.fillStyle = "#11110f88";
    ctx.fillRect(0, 0, 360, 640);
  }
  const glow = ctx.createRadialGradient(180, 255, 10, 180, 255, 300);
  glow.addColorStop(0, color + "cc");
  glow.addColorStop(1, "#11110f00");
  ctx.fillStyle = glow;
  ctx.fillRect(0, 0, 360, 540);
  ctx.save();
  ctx.translate(180, 265);
  ctx.rotate(progress * .5);
  ctx.strokeStyle = color + "66";
  ctx.lineWidth = 35;
  ctx.beginPath();
  ctx.arc(0, 0, 145 + Math.sin(progress * 4) * 8, 0, Math.PI * 1.65);
  ctx.stroke();
  ctx.restore();
  ctx.fillStyle = color;
  roundedRect(ctx, 24, 26, 82, 23, 12);
  ctx.fillStyle = "#11110f";
  ctx.font = "700 9px Manrope";
  ctx.textAlign = "left";
  ctx.textBaseline = "alphabetic";
  ctx.fillText(format.toUpperCase(), 40, 41);

  const hookBlock = fitTextBlock(ctx, hook, 310, 4, 36, 27, 800);
  const hookLineHeight = Math.round(hookBlock.size * 1.08);
  const hookHeight = hookBlock.lines.length * hookLineHeight;
  const hookY = Math.max(250, 405 - hookHeight);
  drawTextBlock(ctx, hookBlock, 25, hookY, hookLineHeight, "#ffffff");

  ctx.globalAlpha = progress === 0 ? 1 : Math.min(1, .45 + progress * 1.8);
  ctx.fillStyle = "#11110fcc";
  roundedRect(ctx, 18, 430, 324, 116, 16);
  ctx.strokeStyle = color + "77";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.roundRect(18.5, 430.5, 323, 115, 15.5);
  ctx.stroke();
  ctx.fillStyle = color;
  ctx.font = "700 8px DM Mono";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText("WHY IT MATTERS", 32, 446);
  const bodyBlock = fitTextBlock(ctx, body, 296, 4, 14, 11, 600);
  drawTextBlock(ctx, bodyBlock, 32, 466, Math.round(bodyBlock.size * 1.28), "#f2efe5");
  ctx.globalAlpha = 1;

  ctx.shadowColor = "#00000066";
  ctx.shadowBlur = 14;
  ctx.shadowOffsetY = 5;
  const ctaGradient = ctx.createLinearGradient(24, 574, 336, 620);
  ctaGradient.addColorStop(0, color);
  ctaGradient.addColorStop(1, "#ffffff");
  ctx.fillStyle = ctaGradient;
  roundedRect(ctx, 24, 574, 312, 46, 23);
  ctx.shadowColor = "transparent";
  ctx.fillStyle = "#11110f";
  const ctaLabel = `${cta}  →`;
  const ctaSize = fitSingleLine(ctx, ctaLabel, 270, 13, 10);
  ctx.font = `800 ${ctaSize}px Manrope`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(ctaLabel, 180, 597);
  ctx.fillStyle = "#ffffff88";
  ctx.font = "500 8px DM Mono";
  ctx.textAlign = "left";
  ctx.textBaseline = "alphabetic";
  ctx.fillText("MADE WITH SIDECLIP", 24, 563);
}

function updatePreview() { drawFrame(state.previewFrame); }

$("#previewPlay").addEventListener("click", () => {
  clearInterval(state.previewTimer);
  const started = performance.now();
  $("#previewPlay").style.display = "none";
  state.previewTimer = setInterval(() => {
    state.previewFrame = ((performance.now() - started) % 5000) / 5000;
    drawFrame(state.previewFrame);
  }, 1000 / 30);
  setTimeout(() => { clearInterval(state.previewTimer); $("#previewPlay").style.display = "block"; state.previewFrame = 0; drawFrame(0); }, 5100);
});

$("#editorForm").addEventListener("submit", async event => {
  event.preventDefault();
  const button = $("#renderButton");
  const status = $("#renderStatus");
  if (!canvas.captureStream || !window.MediaRecorder) {
    status.textContent = "This browser does not support video rendering.";
    return;
  }
  button.disabled = true;
  status.textContent = "Rendering your 6-second clip...";
  const stream = canvas.captureStream(30);
  let audio;
  let audioContext;
  const selectedVoice = state.assets.find(asset => asset.id === state.voiceAsset);
  if (selectedVoice) {
    audio = new Audio(selectedVoice.url);
    audioContext = new AudioContext();
    const source = audioContext.createMediaElementSource(audio);
    const destination = audioContext.createMediaStreamDestination();
    source.connect(destination);
    source.connect(audioContext.destination);
    destination.stream.getAudioTracks().forEach(track => stream.addTrack(track));
  }
  const mimeType = MediaRecorder.isTypeSupported("video/webm;codecs=vp9") ? "video/webm;codecs=vp9" : "video/webm";
  const recorder = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: 3500000 });
  const chunks = [];
  recorder.ondataavailable = e => { if (e.data.size) chunks.push(e.data); };
  recorder.onstop = () => {
    const blob = new Blob(chunks, {type: mimeType});
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `sideclip-${Date.now()}.webm`;
    link.click();
    setTimeout(() => URL.revokeObjectURL(url), 3000);
    button.disabled = false;
    status.textContent = "Done. Your video was downloaded.";
    drawFrame(0);
  };
  recorder.start();
  if (audio) {
    audio.currentTime = 0;
    await audio.play();
  }
  const start = performance.now();
  await new Promise(resolve => {
    const render = now => {
      const elapsed = now - start;
      drawFrame(Math.min(1, elapsed / 6000));
      status.textContent = `Rendering... ${Math.min(100, Math.round(elapsed / 60))}%`;
      if (elapsed < 6000) requestAnimationFrame(render);
      else resolve();
    };
    requestAnimationFrame(render);
  });
  recorder.stop();
  if (audio) audio.pause();
  if (audioContext) audioContext.close();
});

async function loadSession() {
  try {
    const result = await api("/api/me");
    state.user = result.user;
    $("#engineLabel").textContent = result.ai === "ollama" ? "LOCAL AI ACTIVE" : "OFFLINE ENGINE";
    updateAccountUi();
    if (state.user) await Promise.all([loadProjects(), loadAssets()]);
  } catch { toast("SideClip server is unavailable. Guest mode is active."); }
}

function updateAccountUi() {
  $("#accountButton").firstChild.textContent = state.user ? `${state.user.name} ` : "Sign in ";
  $("#authForms").hidden = Boolean(state.user);
  $("#accountPanel").hidden = !state.user;
  if (state.user) {
    $("#accountName").textContent = state.user.name;
    $("#accountEmail").textContent = state.user.email;
  }
}

let registering = false;
$("#accountButton").addEventListener("click", () => $("#authDialog").showModal());
$("#closeAuth").addEventListener("click", () => $("#authDialog").close());
$("#authSwitch").addEventListener("click", () => {
  registering = !registering;
  $(".register-field").style.display = registering ? "flex" : "none";
  $("#authTitle").textContent = registering ? "Create your account" : "Sign in to SideClip";
  $("#authSubmit").textContent = registering ? "Create account" : "Sign in";
  $("#authSwitch").textContent = registering ? "Already have an account? Sign in" : "Need an account? Create one";
  $("#authPassword").autocomplete = registering ? "new-password" : "current-password";
});
$("#authForm").addEventListener("submit", async event => {
  event.preventDefault();
  $("#authMessage").textContent = "";
  try {
    const result = await api(registering ? "/api/register" : "/api/login", {
      method: "POST",
      body: JSON.stringify({ name: $("#authName").value, email: $("#authEmail").value, password: $("#authPassword").value })
    });
    state.user = result.user;
    updateAccountUi();
    $("#authDialog").close();
    toast(`Welcome, ${state.user.name}.`);
    await Promise.all([loadProjects(), loadAssets()]);
  } catch (error) { $("#authMessage").textContent = error.message; }
});
$("#logoutButton").addEventListener("click", async () => {
  await api("/api/logout", { method: "POST" });
  state.user = null; state.projects = []; state.assets = [];
  updateAccountUi(); renderProjects(); renderAssets();
  $("#authDialog").close(); toast("Signed out.");
});
$("#exportDataButton").addEventListener("click", () => {
  const link = document.createElement("a");
  link.href = "/api/export"; link.download = "sideclip-export.json"; link.click();
});
$("#deleteAccountButton").addEventListener("click", async () => {
  if (!confirm("Delete your account, projects, and uploaded media permanently?")) return;
  await api("/api/account", { method: "DELETE" });
  state.user = null; state.projects = []; state.assets = []; state.projectId = null;
  updateAccountUi(); renderProjects(); renderAssets();
  $("#authDialog").close(); toast("Your account and data were deleted.");
});

async function loadProjects() {
  if (!state.user) return renderProjects();
  const result = await api("/api/projects");
  state.projects = result.projects;
  renderProjects();
}
function renderProjects() {
  $("#projectsEmpty").style.display = state.projects.length ? "none" : "block";
  $("#projectsEmpty").querySelector("b").textContent = state.user ? "No saved projects yet." : "Sign in to save your work.";
  $("#projectList").innerHTML = state.projects.map(project => `
    <article class="project-card" data-id="${project.id}">
      <span>${new Date(project.updatedAt).toLocaleDateString()}</span>
      <h4>${escapeHtml(project.name)}</h4>
      <div><button class="ghost-button load-project" type="button">Open</button><button class="ghost-button delete-project" type="button">Delete</button></div>
    </article>`).join("");
  $$(".load-project").forEach(button => button.addEventListener("click", () => loadProject(button.closest("article").dataset.id)));
  $$(".delete-project").forEach(button => button.addEventListener("click", () => deleteProject(button.closest("article").dataset.id)));
}
function projectData() {
  return {
    brief: { product: $("#product").value, description: $("#description").value, audience: $("#audience").value, goal: $("#goal").value },
    plan: state.plan, current: state.current, selectedAsset: state.selectedAsset, voiceAsset: state.voiceAsset
  };
}
async function saveProject() {
  if (!state.user) { $("#authDialog").showModal(); return; }
  const result = await api("/api/projects", { method: "POST", body: JSON.stringify({
    id: state.projectId, name: $("#product").value || "Untitled campaign", data: projectData()
  }) });
  state.projectId = result.project.id;
  toast("Project saved.");
  await loadProjects();
}
function loadProject(projectId) {
  const project = state.projects.find(item => item.id === projectId);
  if (!project) return;
  state.projectId = project.id;
  const data = project.data;
  Object.entries(data.brief || {}).forEach(([key, value]) => { const input = $(`#${key}`); if (input) input.value = value; });
  state.plan = data.plan || [];
  state.voiceAsset = data.voiceAsset || null;
  $("#planCount").textContent = state.plan.length;
  renderPlan();
  if (data.current) openEditor(data.current);
  if (data.selectedAsset) selectAsset(data.selectedAsset);
  toast("Project opened.");
}
async function deleteProject(projectId) {
  if (!confirm("Delete this project permanently?")) return;
  await api(`/api/projects/${projectId}`, { method: "DELETE" });
  if (state.projectId === projectId) state.projectId = null;
  await loadProjects();
}
$("#saveProjectButton").addEventListener("click", saveProject);
$("#refreshProjects").addEventListener("click", loadProjects);

function escapeHtml(value) {
  const div = document.createElement("div");
  div.textContent = String(value || "");
  return div.innerHTML;
}
async function loadAssets() {
  if (!state.user) return renderAssets();
  const result = await api("/api/assets");
  state.assets = result.assets;
  renderAssets();
}
function renderAssets() {
  $("#assetsEmpty").style.display = state.assets.length ? "none" : "block";
  $("#assetList").innerHTML = state.assets.map(asset => `
    <article class="asset-card ${state.selectedAsset === asset.id || state.voiceAsset === asset.id ? "active" : ""}" data-id="${asset.id}">
      ${asset.type.startsWith("image/") ? `<img src="${asset.url}" alt="">` : asset.type.startsWith("video/") ? `<video src="${asset.url}" muted></video>` : `<audio src="${asset.url}" controls></audio>`}
      <span>${escapeHtml(asset.name)}</span>
    </article>`).join("");
  const visualAssets = state.assets.filter(asset => !asset.type.startsWith("audio/"));
  const audioAssets = state.assets.filter(asset => asset.type.startsWith("audio/"));
  $("#editAsset").innerHTML = `<option value="">Procedural animation</option>${visualAssets.map(asset => `<option value="${asset.id}">${escapeHtml(asset.name)}</option>`).join("")}`;
  $("#voiceAsset").innerHTML = `<option value="">No audio track</option>${audioAssets.map(asset => `<option value="${asset.id}">${escapeHtml(asset.name)}</option>`).join("")}`;
  $("#voiceAsset").value = state.voiceAsset || "";
  $$(".asset-card").forEach(card => card.addEventListener("click", event => {
    if (event.target.closest("audio")) return;
    const asset = state.assets.find(item => item.id === card.dataset.id);
    if (asset.type.startsWith("audio/")) {
      state.voiceAsset = asset.id;
      renderAssets();
      toast("Voiceover selected for export.");
    } else selectAsset(asset.id);
  }));
}
async function selectAsset(assetId) {
  state.selectedAsset = assetId || null;
  const asset = state.assets.find(item => item.id === assetId);
  if (!asset) { state.assetElement = null; updatePreview(); return; }
  const element = document.createElement(asset.type.startsWith("image/") ? "img" : "video");
  element.crossOrigin = "same-origin";
  element.src = asset.url;
  element.muted = true;
  element.loop = true;
  await new Promise(resolve => { element.onload = resolve; element.onloadeddata = resolve; });
  if (element.play) element.play().catch(() => {});
  state.assetElement = element;
  $("#editAsset").value = assetId;
  renderAssets(); updatePreview(); toast("Background media selected.");
}
$("#editAsset").addEventListener("change", event => selectAsset(event.target.value));
$("#voiceAsset").addEventListener("change", event => {
  state.voiceAsset = event.target.value || null;
  toast(state.voiceAsset ? "Voiceover selected for export." : "Voiceover removed.");
});
$("#assetUpload").addEventListener("change", async event => {
  const file = event.target.files[0];
  if (!file) return;
  if (!state.user) { $("#authDialog").showModal(); return; }
  if (file.size > 10 * 1024 * 1024) return toast("Files must be under 10 MB.");
  const reader = new FileReader();
  reader.onload = async () => {
    try {
      await api("/api/uploads", { method: "POST", body: JSON.stringify({ name: file.name, type: file.type, data: reader.result }) });
      await loadAssets(); toast("Media uploaded.");
    } catch (error) { toast(error.message); }
  };
  reader.readAsDataURL(file);
});

function populateVoices() {
  const voices = speechSynthesis.getVoices();
  $("#voiceSelect").innerHTML = `<option value="">System default</option>${voices.map(voice => `<option value="${escapeHtml(voice.name)}">${escapeHtml(voice.name)} · ${voice.lang}</option>`).join("")}`;
}
if ("speechSynthesis" in window) {
  populateVoices();
  speechSynthesis.onvoiceschanged = populateVoices;
}
$("#speakButton").addEventListener("click", () => {
  if (!("speechSynthesis" in window)) return toast("Narration is not supported in this browser.");
  speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(`${state.current.hook}. ${state.current.body}. ${state.current.cta}`);
  utterance.voice = speechSynthesis.getVoices().find(voice => voice.name === $("#voiceSelect").value) || null;
  speechSynthesis.speak(utterance);
  $("#previewPlay").click();
});
let voiceRecorder;
let voiceChunks = [];
$("#recordVoiceButton").addEventListener("click", async () => {
  if (voiceRecorder && voiceRecorder.state === "recording") {
    voiceRecorder.stop();
    $("#recordVoiceButton").textContent = "Record voiceover";
    return;
  }
  if (!state.user) { $("#authDialog").showModal(); return; }
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    voiceChunks = [];
    voiceRecorder = new MediaRecorder(stream, { mimeType: MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : "" });
    voiceRecorder.ondataavailable = event => { if (event.data.size) voiceChunks.push(event.data); };
    voiceRecorder.onstop = () => {
      stream.getTracks().forEach(track => track.stop());
      const blob = new Blob(voiceChunks, { type: "audio/webm" });
      const reader = new FileReader();
      reader.onload = async () => {
        try {
          const result = await api("/api/uploads", { method: "POST", body: JSON.stringify({
            name: `Voiceover ${new Date().toLocaleString()}`, type: "audio/webm", data: reader.result
          }) });
          await loadAssets();
          state.voiceAsset = result.asset.id;
          renderAssets();
          toast("Voiceover recorded and selected.");
        } catch (error) { toast(error.message); }
      };
      reader.readAsDataURL(blob);
    };
    voiceRecorder.start();
    $("#recordVoiceButton").textContent = "Stop recording";
    toast("Recording voiceover...");
  } catch { toast("Microphone access is required to record a voiceover."); }
});
function downloadBlob(name, type, content) {
  const link = document.createElement("a");
  link.href = URL.createObjectURL(new Blob([content], { type }));
  link.download = name; link.click();
  setTimeout(() => URL.revokeObjectURL(link.href), 3000);
}
$("#subtitleButton").addEventListener("click", () => {
  const content = `1\n00:00:00,000 --> 00:00:02,500\n${state.current.hook}\n\n2\n00:00:02,500 --> 00:00:05,000\n${state.current.body}\n\n3\n00:00:05,000 --> 00:00:06,000\n${state.current.cta}\n`;
  downloadBlob("sideclip-captions.srt", "text/plain", content);
});
$("#shareButton").addEventListener("click", async () => {
  const text = `${state.current.hook}\n\n${state.current.body}\n\n${state.current.cta}`;
  if (navigator.share) {
    try { await navigator.share({ title: $("#product").value, text }); return; } catch {}
  }
  await navigator.clipboard.writeText(text);
  downloadBlob("sideclip-posting-pack.txt", "text/plain", text);
  toast("Caption copied and posting pack downloaded.");
});
$("#openMediaButton").addEventListener("click", () => showView("assets"));

async function boot() {
  $(".register-field").style.display = "none";
  await generatePlan();
  openEditor(state.plan[0]);
  showView("brief");
  await loadSession();
  if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => {});
}
boot();
