const state = {
  plan: [],
  user: null,
  projects: [],
  assets: [],
  projectId: null,
  selectedAsset: null,
  assetElement: null,
  voiceAsset: null,
  current: {
    format: "Story",
    hook: "Your to-do list isn't the problem.",
    body: "The way you plan your attention is.",
    cta: "Try FocusFlow today →",
    caption: "Your best work deserves a workflow that protects your attention.",
    visual: "orbit",
    color: "#d7ff39"
  },
  previewFrame: 0,
  previewTimer: null
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
let toastTimer;
let persistenceTimer;
let accountSaveTimer;
const DRAFT_KEY = "sideclip-draft-v1";
const LAST_PROJECT_KEY = "sideclip-last-project";

function toast(message) {
  $("#toast").textContent = message;
  $("#toast").classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => $("#toast").classList.remove("show"), 3000);
}

function hasCampaignContent(data = projectData()) {
  return Boolean(String(data.brief?.product || "").trim() || String(data.brief?.description || "").trim() || (data.plan || []).length);
}

function saveLocalDraft() {
  try {
    localStorage.setItem(DRAFT_KEY, JSON.stringify({ ...projectData(), savedAt: new Date().toISOString() }));
  } catch {}
}

function schedulePersistence() {
  clearTimeout(persistenceTimer);
  persistenceTimer = setTimeout(saveLocalDraft, 350);
  if (!state.user || !hasCampaignContent()) return;
  clearTimeout(accountSaveTimer);
  accountSaveTimer = setTimeout(() => saveProject({ silent: true }).catch(() => {}), 1400);
}

async function api(url, options = {}) {
  const response = await fetch(url, {
    credentials: "same-origin",
    headers: { "Content-Type": "application/json", ...(options.headers || {}) },
    ...options
  });
  const result = await response.json();
  if (!response.ok) throw new Error(result.error || "Request failed.");
  return result;
}

function briefInput() {
  return {
    product: $("#product").value, audience: $("#audience").value, description: $("#description").value,
    goal: $("#goal").value, voice: $("#voice").value, avoid: $("#avoid").value
  };
}

function copyQuality(idea) {
  return SideClipGenerator.ideaQuality(idea, briefInput());
}

function planNeedsUpgrade(plan) {
  if (!Array.isArray(plan) || plan.length !== 30) return true;
  if (new Set(plan.map(idea => idea.body)).size !== plan.length) return true;
  return plan.some(idea => !idea.caption || !idea.visual || copyQuality(idea).score < 100);
}

function showView(name) {
  $$(".studio-view").forEach(v => v.classList.remove("active"));
  $$(".side-nav").forEach(v => v.classList.toggle("active", v.dataset.view === name));
  $(`#${name}View`).classList.add("active");
}

$$(".side-nav").forEach(button => button.addEventListener("click", () => {
  if (button.dataset.view === "calendar" && !state.plan.length) generatePlan();
  showView(button.dataset.view);
}));

$$(".choice").forEach(choice => {
  choice.addEventListener("click", () => setTimeout(() => choice.classList.toggle("selected", choice.querySelector("input").checked), 0));
});

async function generatePlan() {
  const description = $("#description").value.trim();
  const values = {
    product: $("#product").value.trim() || "Your product",
    audience: $("#audience").value.trim() || "your audience"
  };
  const submit = $("#briefForm button[type=submit]");
  submit.disabled = true;
  submit.firstChild.textContent = $("#engineLabel").textContent.includes("LOCAL AI")
    ? "Your local AI is writing 30 posts (1-2 min) "
    : "Generating your content plan ";
  try {
    const result = await api("/api/generate", { method: "POST", body: JSON.stringify({
      product: values.product, audience: values.audience, description,
      goal: $("#goal").value, voice: $("#voice").value, avoid: $("#avoid").value
    }) });
    state.plan = result.ideas;
    $("#engineLabel").textContent = result.engine === "ollama" ? "LOCAL AI ACTIVE" : "OFFLINE ENGINE";
    $("#engineDescription").textContent = result.engine === "ollama" ? "Ideas generated by your private Ollama model." : "Template engine active. Connect free local Ollama for stronger generation.";
  } catch {
    state.plan = SideClipGenerator.localIdeas({
      product: values.product, audience: values.audience, description,
      goal: $("#goal").value, voice: $("#voice").value, avoid: $("#avoid").value
    });
    $("#engineLabel").textContent = "OFFLINE ENGINE";
    $("#engineDescription").textContent = "On-device generator active. Start the SideClip server to save projects or use local AI.";
    toast("Server unreachable. Generated your plan on this device instead.");
  } finally {
    submit.disabled = false;
    submit.firstChild.textContent = "Generate my content plan ";
  }
  $("#planCount").textContent = "30";
  renderPlan();
  schedulePersistence();
}

$("#briefForm").addEventListener("submit", async event => {
  event.preventDefault();
  await generatePlan();
  showView("calendar");
});
$("#briefForm").addEventListener("input", schedulePersistence);
$("#briefForm").addEventListener("change", schedulePersistence);

function renderPlan(filter = "All") {
  const items = filter === "All" ? state.plan : state.plan.filter(item => item.format === filter);
  const qualities = new Map(state.plan.map(item => [item.day, copyQuality(item)]));
  $("#calendarList").innerHTML = items.map(item => {
    const format = ["Story", "Educate", "Promote"].includes(item.format) ? item.format : "Story";
    const quality = qualities.get(item.day) || copyQuality(item);
    return `
    <article class="calendar-card" data-day="${Number(item.day) || 0}">
      <span class="calendar-day">DAY ${String(item.day).padStart(2, "0")}</span>
      <span class="type-pill ${format}">${format.toUpperCase()}</span>
      <strong>${escapeHtml(item.hook)}</strong>
      <span class="score-chip ${quality.score === 100 ? "ready" : "attention"}" title="Publish readiness">${quality.score}</span>
      <button aria-label="Edit day ${Number(item.day) || 0}">→</button>
    </article>`;
  }).join("");
  $$(".calendar-card").forEach(card => card.addEventListener("click", () => openEditor(state.plan.find(item => item.day === Number(card.dataset.day)))));
  updatePlanReadiness(qualities);
}

function updatePlanReadiness(qualities = new Map(state.plan.map(item => [item.day, copyQuality(item)]))) {
  const summary = $("#planReadiness");
  if (!state.plan.length) { summary.textContent = ""; return; }
  const scores = [...qualities.values()];
  const average = Math.round(scores.reduce((sum, quality) => sum + quality.score, 0) / scores.length);
  const needsWork = scores.filter(quality => quality.issues.length).length;
  const topIssues = [...new Set(scores.flatMap(quality => quality.issues))].slice(0, 2).join(" ");
  summary.textContent = needsWork
    ? `Plan readiness ${average}/100 · ${needsWork} of ${state.plan.length} posts need attention. ${topIssues}`
    : `Plan readiness 100/100 · All ${state.plan.length} posts are specific, complete, and ready to publish.`;
}

$$(".filter").forEach(button => button.addEventListener("click", () => {
  $$(".filter").forEach(b => b.classList.remove("active"));
  button.classList.add("active");
  renderPlan(button.dataset.filter);
}));

$("#newBrief").addEventListener("click", () => showView("brief"));
$("#backToPlan").addEventListener("click", () => showView("calendar"));

function openEditor(item) {
  state.current = {...item, caption: item.caption || `${item.hook}\n\n${item.body}\n\n${item.cta}.`, sourceCaption: item.caption || `${item.hook}\n\n${item.body}\n\n${item.cta}.`, captionVariant: 0, visual: item.visual || "orbit", color: item.color || (item.format === "Story" ? "#ff725c" : item.format === "Educate" ? "#7095ff" : "#d7ff39")};
  $("#editFormat").value = state.current.format;
  $("#editHook").value = state.current.hook;
  $("#editBody").value = state.current.body;
  $("#editCta").value = state.current.cta;
  $("#editCaption").value = state.current.caption;
  $("#editColor").value = state.current.color;
  $("#visualStyle").value = state.current.visual;
  updateQualityUi();
  updatePreview();
  showView("editor");
}

["editFormat", "editHook", "editBody", "editCta", "editCaption", "editColor", "visualStyle"].forEach(id => {
  $(`#${id}`).addEventListener("input", () => {
    state.current = {
      ...state.current,
      format: $("#editFormat").value,
      hook: $("#editHook").value,
      body: $("#editBody").value,
      cta: $("#editCta").value,
      caption: $("#editCaption").value,
      color: $("#editColor").value,
      visual: $("#visualStyle").value
    };
    const planItem = state.plan.find(item => item.day === state.current.day);
    if (planItem) Object.assign(planItem, state.current);
    updateQualityUi();
    updatePreview();
    schedulePersistence();
  });
});

function updateQualityUi() {
  const quality = copyQuality(state.current);
  $("#hookCount").textContent = `${state.current.hook.length} / 105`;
  $("#bodyCount").textContent = `${state.current.body.length} / 145`;
  $("#ctaCount").textContent = `${state.current.cta.length} / 34`;
  $("#captionCount").textContent = `${state.current.caption.length} / 1600`;
  $("#qualityScore").textContent = `Publish readiness: ${quality.score}`;
  const advisories = quality.issues.filter(issue => !quality.blockers.includes(issue));
  $("#qualityIssues").textContent = quality.blockers.length
    ? `Fix before rendering: ${quality.blockers.join(" ")}${advisories.length ? ` Then strengthen it: ${advisories.join(" ")}` : ""}`
    : advisories.length
      ? `Ready to render. Make it stronger: ${advisories.join(" ")}`
      : "Specific, relevant, complete, and ready to render.";
  $("#qualityPanel").classList.toggle("warning", quality.issues.length > 0);
  $("#renderButton").disabled = quality.blockers.length > 0;
}

const canvas = $("#previewCanvas");
const ctx = canvas.getContext("2d");

function roundedRect(context, x, y, w, h, r) {
  context.beginPath();
  context.roundRect(x, y, w, h, r);
  context.fill();
}

function wrapText(context, text, maxWidth) {
  const words = text.split(" ").flatMap(word => {
    if (context.measureText(word).width <= maxWidth) return [word];
    const chunks = [];
    let chunk = "";
    for (const character of word) {
      if (context.measureText(chunk + character).width > maxWidth && chunk) {
        chunks.push(chunk);
        chunk = character;
      } else chunk += character;
    }
    if (chunk) chunks.push(chunk);
    return chunks;
  });
  const lines = [];
  let line = "";
  words.forEach(word => {
    const test = line ? `${line} ${word}` : word;
    if (context.measureText(test).width > maxWidth && line) {
      lines.push(line);
      line = word;
    } else line = test;
  });
  if (line) lines.push(line);
  return lines;
}

function fitTextBlock(context, text, maxWidth, startSize, minSize, weight, lineFactor, maxHeight) {
  for (let size = startSize; size >= minSize; size -= 1) {
    context.font = `${weight} ${size}px Manrope`;
    const lines = wrapText(context, text, maxWidth);
    const lineHeight = Math.round(size * lineFactor);
    if (lines.length * lineHeight <= maxHeight) return { lines, size, lineHeight, font: context.font };
  }
  context.font = `${weight} ${minSize}px Manrope`;
  const lineHeight = Math.round(minSize * lineFactor);
  const lines = wrapText(context, text, maxWidth).slice(0, Math.max(1, Math.floor(maxHeight / lineHeight)));
  return { lines, size: minSize, lineHeight, font: context.font };
}

function drawTextBlock(context, block, x, y, color) {
  context.fillStyle = color;
  context.font = block.font;
  context.textAlign = "left";
  context.textBaseline = "top";
  block.lines.forEach((line, index) => context.fillText(line, x, y + index * block.lineHeight));
}

function fitSingleLine(context, text, maxWidth, startSize, minSize, weight = 800) {
  let size = startSize;
  while (size > minSize) {
    context.font = `${weight} ${size}px Manrope`;
    if (context.measureText(text).width <= maxWidth) break;
    size -= 1;
  }
  return size;
}

function drawProcedural(context, style, progress, color) {
  const p = progress * Math.PI * 2;
  const glow = context.createRadialGradient(180, 245, 10, 180, 245, 300);
  glow.addColorStop(0, color + "b8");
  glow.addColorStop(1, "#11110f00");
  context.fillStyle = glow;
  context.fillRect(0, 0, 360, 430);
  context.save();
  context.strokeStyle = color + "70";
  context.fillStyle = color + "30";

  if (style === "checklist") {
    [120, 190, 260, 330].forEach((y, index) => {
      const offset = Math.sin(p + index) * 7;
      context.fillStyle = "#ffffff10";
      context.beginPath(); context.roundRect(45 + offset, y, 270, 48, 12); context.fill();
      context.fillStyle = color;
      context.beginPath(); context.arc(68 + offset, y + 24, 10, 0, Math.PI * 2); context.fill();
      context.strokeStyle = "#11110f"; context.lineWidth = 3;
      context.beginPath(); context.moveTo(63 + offset, y + 24); context.lineTo(67 + offset, y + 28); context.lineTo(74 + offset, y + 19); context.stroke();
      context.fillStyle = "#ffffff35"; context.fillRect(91 + offset, y + 17, 155 - index * 15, 5); context.fillRect(91 + offset, y + 29, 105 + index * 12, 4);
    });
  } else if (style === "spotlight") {
    [0, 1, 2].forEach(index => {
      const x = 90 + index * 90 + Math.sin(p + index * 2) * 25;
      const y = 210 + Math.cos(p + index) * 45;
      const radial = context.createRadialGradient(x, y, 5, x, y, 75);
      radial.addColorStop(0, color + "aa"); radial.addColorStop(1, color + "00");
      context.fillStyle = radial; context.fillRect(x - 80, y - 80, 160, 160);
    });
  } else if (style === "cards") {
    [-1, 0, 1].forEach((index, position) => {
      context.save();
      context.translate(180 + index * 82, 225 + Math.sin(p + position) * 12);
      context.rotate(index * .12 + Math.sin(p) * .025);
      context.fillStyle = position === 1 ? color + "aa" : "#ffffff16";
      context.beginPath(); context.roundRect(-52, -78, 104, 156, 15); context.fill();
      context.strokeStyle = "#ffffff30"; context.stroke();
      context.restore();
    });
  } else if (style === "grid") {
    context.lineWidth = 1;
    for (let x = 20; x < 360; x += 42) { context.beginPath(); context.moveTo(x, 75); context.lineTo(x, 410); context.stroke(); }
    for (let y = 75; y < 420; y += 42) { context.beginPath(); context.moveTo(15, y); context.lineTo(345, y); context.stroke(); }
    for (let index = 0; index < 7; index++) {
      context.fillStyle = index % 2 ? color : "#ffffff";
      context.beginPath(); context.arc(54 + index * 42, 117 + ((index * 3) % 6) * 42, 4 + Math.sin(p + index) * 2, 0, Math.PI * 2); context.fill();
    }
  } else if (style === "waves") {
    context.lineWidth = 3;
    for (let row = 0; row < 7; row++) {
      context.beginPath();
      for (let x = 0; x <= 360; x += 8) {
        const y = 130 + row * 38 + Math.sin(x / 35 + p + row * .7) * 18;
        x ? context.lineTo(x, y) : context.moveTo(x, y);
      }
      context.stroke();
    }
  } else {
    context.translate(180, 240);
    context.rotate(progress * .5);
    context.lineWidth = 35;
    context.beginPath();
    context.arc(0, 0, 145 + Math.sin(progress * 4) * 8, 0, Math.PI * 1.65);
    context.stroke();
  }
  context.restore();
}

function drawFrame(progress = 0) {
  const { format, hook, body, cta, color, visual = "orbit" } = state.current;
  const scale = canvas.width / 360;
  const quality = copyQuality(state.current);
  const bodyFits = !quality.issues.some(issue => issue.startsWith("Supporting line must be"));
  const renderBody = bodyFits ? body : "Supporting line must be 45-145 characters before rendering.";
  ctx.setTransform(1, 0, 0, 1, 0, 0);
  ctx.fillStyle = "#11110f";
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.setTransform(scale, 0, 0, scale, 0, 0);
  drawProcedural(ctx, visual, progress, color);
  if (state.assetElement) {
    const media = state.assetElement;
    const sourceWidth = media.videoWidth || media.naturalWidth || 360;
    const sourceHeight = media.videoHeight || media.naturalHeight || 640;
    const scale = Math.max(360 / sourceWidth, 640 / sourceHeight);
    const width = sourceWidth * scale;
    const height = sourceHeight * scale;
    ctx.globalAlpha = .48;
    ctx.drawImage(media, (360 - width) / 2, (640 - height) / 2, width, height);
    ctx.globalAlpha = 1;
    ctx.fillStyle = "#11110f88";
    ctx.fillRect(0, 0, 360, 640);
  }
  ctx.fillStyle = color;
  roundedRect(ctx, 24, 26, 82, 23, 12);
  ctx.fillStyle = "#11110f";
  ctx.font = "700 9px Manrope";
  ctx.textAlign = "left";
  ctx.textBaseline = "alphabetic";
  ctx.fillText(format.toUpperCase(), 40, 41);

  const hookBlock = fitTextBlock(ctx, hook, 310, 34, 13, 800, 1.08, 244);
  const hookHeight = hookBlock.lines.length * hookBlock.lineHeight;
  const hookY = Math.max(170, 414 - hookHeight);
  ctx.save();
  ctx.beginPath();
  ctx.rect(18, 160, 324, 260);
  ctx.clip();
  drawTextBlock(ctx, hookBlock, 25, hookY, "#ffffff");
  ctx.restore();

  ctx.globalAlpha = progress === 0 ? 1 : Math.min(1, .45 + progress * 1.8);
  ctx.fillStyle = "#11110fcc";
  roundedRect(ctx, 18, 430, 324, 116, 16);
  ctx.strokeStyle = color + "77";
  ctx.lineWidth = 1;
  ctx.beginPath();
  ctx.roundRect(18.5, 430.5, 323, 115, 15.5);
  ctx.stroke();
  ctx.fillStyle = color;
  ctx.font = "700 8px DM Mono";
  ctx.textAlign = "left";
  ctx.textBaseline = "top";
  ctx.fillText("WHY IT MATTERS", 32, 446);
  const bodyBlock = fitTextBlock(ctx, renderBody, 296, 14, 9, 600, 1.28, 70);
  ctx.save();
  ctx.beginPath();
  ctx.rect(30, 464, 300, 72);
  ctx.clip();
  drawTextBlock(ctx, bodyBlock, 32, 466, bodyFits ? "#f2efe5" : "#ff927f");
  ctx.restore();
  ctx.globalAlpha = 1;

  ctx.shadowColor = "#00000066";
  ctx.shadowBlur = 14 * scale;
  ctx.shadowOffsetY = 5 * scale;
  const ctaGradient = ctx.createLinearGradient(24, 574, 336, 620);
  ctaGradient.addColorStop(0, color);
  ctaGradient.addColorStop(1, "#ffffff");
  ctx.fillStyle = ctaGradient;
  roundedRect(ctx, 24, 574, 312, 46, 23);
  ctx.shadowColor = "transparent";
  ctx.fillStyle = "#11110f";
  const ctaLabel = `${cta}  →`;
  const ctaSize = fitSingleLine(ctx, ctaLabel, 270, 13, 10);
  ctx.font = `800 ${ctaSize}px Manrope`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(ctaLabel, 180, 597);
  ctx.fillStyle = "#ffffff88";
  ctx.font = "500 8px DM Mono";
  ctx.textAlign = "left";
  ctx.textBaseline = "alphabetic";
  ctx.fillText("MADE WITH SIDECLIP", 24, 563);
}

function updatePreview() { drawFrame(state.previewFrame); }

$("#previewPlay").addEventListener("click", () => {
  clearInterval(state.previewTimer);
  const started = performance.now();
  $("#previewPlay").style.display = "none";
  state.previewTimer = setInterval(() => {
    state.previewFrame = ((performance.now() - started) % 5000) / 5000;
    drawFrame(state.previewFrame);
  }, 1000 / 30);
  setTimeout(() => { clearInterval(state.previewTimer); $("#previewPlay").style.display = "block"; state.previewFrame = 0; drawFrame(0); }, 5100);
});

$("#editorForm").addEventListener("submit", async event => {
  event.preventDefault();
  const button = $("#renderButton");
  const status = $("#renderStatus");
  if (!canvas.captureStream || !window.MediaRecorder) {
    status.textContent = "This browser does not support video rendering.";
    return;
  }
  button.disabled = true;
  status.textContent = "Rendering your 6-second clip...";
  const stream = canvas.captureStream(30);
  let audio;
  let audioContext;
  const selectedVoice = state.assets.find(asset => asset.id === state.voiceAsset);
  if (selectedVoice) {
    audio = new Audio(selectedVoice.url);
    audioContext = new AudioContext();
    const source = audioContext.createMediaElementSource(audio);
    const destination = audioContext.createMediaStreamDestination();
    source.connect(destination);
    source.connect(audioContext.destination);
    destination.stream.getAudioTracks().forEach(track => stream.addTrack(track));
  }
  const mimeType = MediaRecorder.isTypeSupported("video/webm;codecs=vp9") ? "video/webm;codecs=vp9" : "video/webm";
  const recorder = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: 8000000 });
  const chunks = [];
  recorder.ondataavailable = e => { if (e.data.size) chunks.push(e.data); };
  recorder.onstop = () => {
    const blob = new Blob(chunks, {type: mimeType});
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `sideclip-${Date.now()}.webm`;
    link.click();
    setTimeout(() => URL.revokeObjectURL(url), 3000);
    button.disabled = false;
    status.textContent = "Done. Your video was downloaded.";
    drawFrame(0);
  };
  recorder.start();
  if (audio) {
    audio.currentTime = 0;
    await audio.play();
  }
  const start = performance.now();
  await new Promise(resolve => {
    const render = now => {
      const elapsed = now - start;
      drawFrame(Math.min(1, elapsed / 6000));
      status.textContent = `Rendering... ${Math.min(100, Math.round(elapsed / 60))}%`;
      if (elapsed < 6000) requestAnimationFrame(render);
      else resolve();
    };
    requestAnimationFrame(render);
  });
  recorder.stop();
  if (audio) audio.pause();
  if (audioContext) audioContext.close();
});

async function loadSession() {
  try {
    const result = await api("/api/me");
    state.user = result.user;
    $("#engineLabel").textContent = result.ai === "ollama" ? "LOCAL AI ACTIVE" : "OFFLINE ENGINE";
    $("#engineDescription").textContent = `${result.ai === "ollama" ? "Private Ollama generation" : "Quality-gated local generation"} · v${result.version || "1.2.0"}`;
    updateAccountUi();
    if (state.user) {
      await Promise.all([loadProjects(), loadAssets()]);
      const lastProject = localStorage.getItem(LAST_PROJECT_KEY);
      const project = state.projects.find(item => item.id === lastProject) || state.projects[0];
      if (project) await loadProject(project.id, { quiet: true });
      else if (hasCampaignContent()) await saveProject({ silent: true });
    }
  } catch { toast("SideClip server is unavailable. Guest mode is active."); }
}

function updateAccountUi() {
  $("#accountButton").firstChild.textContent = state.user ? `${state.user.name} ` : "Sign in ";
  $("#authForms").hidden = Boolean(state.user);
  $("#accountPanel").hidden = !state.user;
  if (state.user) {
    $("#accountName").textContent = state.user.name;
    $("#accountEmail").textContent = state.user.email;
  }
}

let registering = false;
$("#accountButton").addEventListener("click", () => $("#authDialog").showModal());
$("#closeAuth").addEventListener("click", () => $("#authDialog").close());
$("#authSwitch").addEventListener("click", () => {
  registering = !registering;
  $(".register-field").style.display = registering ? "flex" : "none";
  $("#authTitle").textContent = registering ? "Create your account" : "Sign in to SideClip";
  $("#authSubmit").textContent = registering ? "Create account" : "Sign in";
  $("#authSwitch").textContent = registering ? "Already have an account? Sign in" : "Need an account? Create one";
  $("#authPassword").autocomplete = registering ? "new-password" : "current-password";
});
$("#authForm").addEventListener("submit", async event => {
  event.preventDefault();
  $("#authMessage").textContent = "";
  try {
    const result = await api(registering ? "/api/register" : "/api/login", {
      method: "POST",
      body: JSON.stringify({ name: $("#authName").value, email: $("#authEmail").value, password: $("#authPassword").value })
    });
    state.user = result.user;
    updateAccountUi();
    $("#authDialog").close();
    toast(`Welcome, ${state.user.name}.`);
    await Promise.all([loadProjects(), loadAssets()]);
    if (state.projects.length) await loadProject(state.projects[0].id, { quiet: true });
    else if (hasCampaignContent()) await saveProject({ silent: true });
  } catch (error) { $("#authMessage").textContent = error.message; }
});
$("#logoutButton").addEventListener("click", async () => {
  await api("/api/logout", { method: "POST" });
  state.user = null; state.projects = []; state.assets = [];
  updateAccountUi(); renderProjects(); renderAssets();
  $("#authDialog").close(); toast("Signed out.");
});
$("#exportDataButton").addEventListener("click", () => {
  const link = document.createElement("a");
  link.href = "/api/export"; link.download = "sideclip-export.json"; link.click();
});
$("#deleteAccountButton").addEventListener("click", async () => {
  if (!confirm("Delete your account, projects, and uploaded media permanently?")) return;
  await api("/api/account", { method: "DELETE" });
  state.user = null; state.projects = []; state.assets = []; state.projectId = null;
  updateAccountUi(); renderProjects(); renderAssets();
  $("#authDialog").close(); toast("Your account and data were deleted.");
});

async function loadProjects() {
  if (!state.user) return renderProjects();
  const result = await api("/api/projects");
  state.projects = result.projects;
  renderProjects();
}
function renderProjects() {
  $("#projectsEmpty").style.display = state.projects.length ? "none" : "block";
  $("#projectsEmpty").querySelector("b").textContent = state.user ? "No saved projects yet." : "Sign in to sync your automatic device draft.";
  $("#projectList").innerHTML = state.projects.map(project => `
    <article class="project-card" data-id="${project.id}">
      <span>${new Date(project.updatedAt).toLocaleDateString()}</span>
      <h4>${escapeHtml(project.name)}</h4>
      <div><button class="ghost-button load-project" type="button">Open</button><button class="ghost-button delete-project" type="button">Delete</button></div>
    </article>`).join("");
  $$(".load-project").forEach(button => button.addEventListener("click", () => loadProject(button.closest("article").dataset.id)));
  $$(".delete-project").forEach(button => button.addEventListener("click", () => deleteProject(button.closest("article").dataset.id)));
}
function projectData() {
  return {
    brief: { product: $("#product").value, description: $("#description").value, audience: $("#audience").value, goal: $("#goal").value, voice: $("#voice").value, avoid: $("#avoid").value },
    plan: state.plan, current: state.current, selectedAsset: state.selectedAsset, voiceAsset: state.voiceAsset
  };
}
async function saveProject(options = {}) {
  if (!state.user) {
    saveLocalDraft();
    if (!options.silent) $("#authDialog").showModal();
    return;
  }
  const result = await api("/api/projects", { method: "POST", body: JSON.stringify({
    id: state.projectId, name: $("#product").value || "Untitled campaign", data: projectData()
  }) });
  state.projectId = result.project.id;
  localStorage.setItem(LAST_PROJECT_KEY, state.projectId);
  const index = state.projects.findIndex(project => project.id === state.projectId);
  if (index >= 0) state.projects[index] = result.project;
  else state.projects.unshift(result.project);
  renderProjects();
  if (!options.silent) toast("Project saved.");
}
function applyProjectData(data) {
  Object.entries(data.brief || {}).forEach(([key, value]) => { const input = $(`#${key}`); if (input) input.value = value; });
  state.plan = data.plan || [];
  state.voiceAsset = data.voiceAsset || null;
  $("#planCount").textContent = state.plan.length;
  renderPlan();
  if (data.current) openEditor(data.current);
  else if (state.plan.length) openEditor(state.plan[0]);
  if (data.selectedAsset) selectAsset(data.selectedAsset);
}
function restoreLocalDraft() {
  try {
    const draft = JSON.parse(localStorage.getItem(DRAFT_KEY) || "null");
    if (!draft || !hasCampaignContent(draft)) return false;
    state.projectId = null;
    applyProjectData(draft);
    return true;
  } catch {
    return false;
  }
}
async function loadProject(projectId, options = {}) {
  const project = state.projects.find(item => item.id === projectId);
  if (!project) return;
  state.projectId = project.id;
  localStorage.setItem(LAST_PROJECT_KEY, project.id);
  applyProjectData(project.data || {});
  saveLocalDraft();
  if (!options.quiet) toast("Project opened exactly as saved.");
}
async function deleteProject(projectId) {
  if (!confirm("Delete this project permanently?")) return;
  await api(`/api/projects/${projectId}`, { method: "DELETE" });
  if (state.projectId === projectId) {
    state.projectId = null;
    localStorage.removeItem(LAST_PROJECT_KEY);
  }
  await loadProjects();
}
$("#saveProjectButton").addEventListener("click", saveProject);
$("#refreshProjects").addEventListener("click", loadProjects);
$("#regeneratePlan").addEventListener("click", async () => {
  await generatePlan();
  state.projectId = null;
  showView("calendar");
  toast("Generated a fresh plan with product-specific hooks.");
});

function escapeHtml(value) {
  const div = document.createElement("div");
  div.textContent = String(value || "");
  return div.innerHTML;
}
async function loadAssets() {
  if (!state.user) return renderAssets();
  const result = await api("/api/assets");
  state.assets = result.assets;
  renderAssets();
}
function renderAssets() {
  $("#assetsEmpty").style.display = state.assets.length ? "none" : "block";
  $("#assetList").innerHTML = state.assets.map(asset => `
    <article class="asset-card ${state.selectedAsset === asset.id || state.voiceAsset === asset.id ? "active" : ""}" data-id="${asset.id}">
      ${asset.type.startsWith("image/") ? `<img src="${asset.url}" alt="">` : asset.type.startsWith("video/") ? `<video src="${asset.url}" muted></video>` : `<audio src="${asset.url}" controls></audio>`}
      <span>${escapeHtml(asset.name)}</span>
    </article>`).join("");
  const visualAssets = state.assets.filter(asset => !asset.type.startsWith("audio/"));
  const audioAssets = state.assets.filter(asset => asset.type.startsWith("audio/"));
  $("#editAsset").innerHTML = `<option value="">Procedural animation</option>${visualAssets.map(asset => `<option value="${asset.id}">${escapeHtml(asset.name)}</option>`).join("")}`;
  $("#voiceAsset").innerHTML = `<option value="">No audio track</option>${audioAssets.map(asset => `<option value="${asset.id}">${escapeHtml(asset.name)}</option>`).join("")}`;
  $("#voiceAsset").value = state.voiceAsset || "";
  $$(".asset-card").forEach(card => card.addEventListener("click", event => {
    if (event.target.closest("audio")) return;
    const asset = state.assets.find(item => item.id === card.dataset.id);
    if (asset.type.startsWith("audio/")) {
      state.voiceAsset = asset.id;
      renderAssets();
      schedulePersistence();
      toast("Voiceover selected for export.");
    } else selectAsset(asset.id);
  }));
}
async function selectAsset(assetId) {
  state.selectedAsset = assetId || null;
  const asset = state.assets.find(item => item.id === assetId);
  if (!asset) { state.assetElement = null; updatePreview(); schedulePersistence(); return; }
  const element = document.createElement(asset.type.startsWith("image/") ? "img" : "video");
  element.crossOrigin = "same-origin";
  element.src = asset.url;
  element.muted = true;
  element.loop = true;
  await new Promise(resolve => { element.onload = resolve; element.onloadeddata = resolve; element.onerror = resolve; });
  if (element.play) element.play().catch(() => {});
  state.assetElement = element;
  $("#editAsset").value = assetId;
  renderAssets(); updatePreview(); schedulePersistence(); toast("Background media selected.");
}
$("#editAsset").addEventListener("change", event => selectAsset(event.target.value));
$("#voiceAsset").addEventListener("change", event => {
  state.voiceAsset = event.target.value || null;
  schedulePersistence();
  toast(state.voiceAsset ? "Voiceover selected for export." : "Voiceover removed.");
});
$("#assetUpload").addEventListener("change", async event => {
  const file = event.target.files[0];
  if (!file) return;
  if (!state.user) { $("#authDialog").showModal(); return; }
  if (file.size > 10 * 1024 * 1024) return toast("Files must be under 10 MB.");
  const reader = new FileReader();
  reader.onload = async () => {
    try {
      await api("/api/uploads", { method: "POST", body: JSON.stringify({ name: file.name, type: file.type, data: reader.result }) });
      await loadAssets(); toast("Media uploaded.");
    } catch (error) { toast(error.message); }
  };
  reader.readAsDataURL(file);
});

function populateVoices() {
  const selected = $("#voiceSelect").value;
  const voices = speechSynthesis.getVoices().sort((a, b) => voiceScore(b) - voiceScore(a) || a.name.localeCompare(b.name));
  const options = voices.map(voice => {
    const recommended = voiceScore(voice) >= 5 ? "Recommended - " : "";
    return `<option value="${escapeHtml(voice.name)}">${recommended}${escapeHtml(voice.name)} · ${voice.lang}</option>`;
  }).join("");
  $("#voiceSelect").innerHTML = `<option value="">System default</option>${options}`;
  if (selected && voices.some(voice => voice.name === selected)) $("#voiceSelect").value = selected;
  else {
    const naturalVoice = voices.find(voice => voiceScore(voice) >= 5);
    if (naturalVoice) $("#voiceSelect").value = naturalVoice.name;
  }
}
function voiceScore(voice) {
  const name = voice.name.toLowerCase();
  let score = 0;
  if (/natural|neural|enhanced|premium|online/.test(name)) score += 8;
  if (/aria|ava|andrew|brian|emma|guy|jenny|michelle|ryan|sonia|steffan/.test(name)) score += 4;
  if (/english|en-us|en-gb|en-au|en-ca/.test(`${name} ${voice.lang.toLowerCase()}`)) score += 2;
  if (/compact|espeak|festival/.test(name)) score -= 5;
  return score;
}
if ("speechSynthesis" in window) {
  populateVoices();
  speechSynthesis.onvoiceschanged = populateVoices;
}
$("#speakButton").addEventListener("click", () => {
  if (!("speechSynthesis" in window)) return toast("Narration is not supported in this browser.");
  speechSynthesis.cancel();
  const utterance = new SpeechSynthesisUtterance(`${state.current.hook}. ${state.current.body}. ${state.current.cta}`);
  utterance.voice = speechSynthesis.getVoices().find(voice => voice.name === $("#voiceSelect").value) || null;
  utterance.rate = Number($("#voiceRate").value);
  utterance.pitch = Number($("#voicePitch").value);
  speechSynthesis.speak(utterance);
  $("#previewPlay").click();
});
let voiceRecorder;
let voiceChunks = [];
$("#recordVoiceButton").addEventListener("click", async () => {
  if (voiceRecorder && voiceRecorder.state === "recording") {
    voiceRecorder.stop();
    $("#recordVoiceButton").textContent = "Record voiceover";
    return;
  }
  if (!state.user) { $("#authDialog").showModal(); return; }
  try {
    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
    voiceChunks = [];
    voiceRecorder = new MediaRecorder(stream, { mimeType: MediaRecorder.isTypeSupported("audio/webm") ? "audio/webm" : "" });
    voiceRecorder.ondataavailable = event => { if (event.data.size) voiceChunks.push(event.data); };
    voiceRecorder.onstop = () => {
      stream.getTracks().forEach(track => track.stop());
      const blob = new Blob(voiceChunks, { type: "audio/webm" });
      const reader = new FileReader();
      reader.onload = async () => {
        try {
          const result = await api("/api/uploads", { method: "POST", body: JSON.stringify({
            name: `Voiceover ${new Date().toLocaleString()}`, type: "audio/webm", data: reader.result
          }) });
          await loadAssets();
          state.voiceAsset = result.asset.id;
          renderAssets();
          toast("Voiceover recorded and selected.");
        } catch (error) { toast(error.message); }
      };
      reader.readAsDataURL(blob);
    };
    voiceRecorder.start();
    $("#recordVoiceButton").textContent = "Stop recording";
    toast("Recording voiceover...");
  } catch { toast("Microphone access is required to record a voiceover."); }
});
function downloadBlob(name, type, content) {
  const link = document.createElement("a");
  link.href = URL.createObjectURL(new Blob([content], { type }));
  link.download = name; link.click();
  setTimeout(() => URL.revokeObjectURL(link.href), 3000);
}
function srtTime(ms) {
  const hours = String(Math.floor(ms / 3600000)).padStart(2, "0");
  const minutes = String(Math.floor(ms / 60000) % 60).padStart(2, "0");
  const seconds = String(Math.floor(ms / 1000) % 60).padStart(2, "0");
  return `${hours}:${minutes}:${seconds},${String(Math.round(ms % 1000)).padStart(3, "0")}`;
}
$("#subtitleButton").addEventListener("click", () => {
  const parts = [state.current.hook, state.current.body, state.current.cta];
  const weights = parts.map(text => Math.max(1, String(text).trim().split(/\s+/).length));
  const total = weights.reduce((sum, count) => sum + count, 0);
  let cursor = 0;
  const content = parts.map((text, index) => {
    const start = cursor;
    cursor = index === parts.length - 1 ? 6000 : Math.min(5500, cursor + Math.round((weights[index] / total) * 6000));
    return `${index + 1}\n${srtTime(start)} --> ${srtTime(cursor)}\n${text}\n`;
  }).join("\n");
  downloadBlob("sideclip-captions.srt", "text/plain", content);
});
function platformCaption(platform) {
  const details = state.current.sourceCaption || state.current.caption || `${state.current.body}\n\n${state.current.cta}.`;
  const product = $("#product").value.trim() || "your business";
  const audience = $("#audience").value.trim() || "your audience";
  const variant = state.current.captionVariant || 0;
  const tags = `#${product.replace(/[^a-z0-9]/gi, "")} #ContentMarketing #SmallBusiness`;
  const nextStep = state.current.cta.replace(/[.!?]+$/, "").replace(/^./, letter => letter.toLowerCase());
  const openers = [
    `For ${audience}, this is worth knowing:`,
    `A practical look at ${product}:`,
    `Before you decide, consider this:`,
    `Here is the useful takeaway for ${audience}:`
  ];
  const closers = [
    `The next step: ${nextStep}.`,
    `Save this for later, then ${nextStep}.`,
    `Share this with someone who would benefit, then ${nextStep}.`,
    `${state.current.body}\n\nReady when you are: ${nextStep}.`
  ];
  const variants = {
    balanced: `${openers[variant % openers.length]}\n\n${details}\n\n${closers[variant % closers.length]}`,
    linkedin: `${openers[(variant + 1) % openers.length]}\n\n${details}\n\n${closers[(variant + 1) % closers.length]}\n\nQuestion: what part of this matters most to you?\n\n${tags}`,
    instagram: `Save this before your next post.\n\n${details}\n\n${closers[(variant + 2) % closers.length]}\n\n${tags} #SocialMediaTips`,
    tiktok: `Quick breakdown:\n\n${details}\n\n${closers[(variant + 3) % closers.length]}\n\n${tags} #LearnOnTikTok`
  };
  return variants[platform].slice(0, 1600);
}
$("#adaptCaptionButton").addEventListener("click", () => {
  state.current.captionVariant = (state.current.captionVariant || 0) + 1;
  state.current.caption = platformCaption($("#captionPlatform").value);
  $("#editCaption").value = state.current.caption;
  updateQualityUi();
  schedulePersistence();
  toast("Caption adapted with a fresh accurate angle.");
});
$("#shareButton").addEventListener("click", async () => {
  const text = state.current.caption;
  if (navigator.share) {
    try { await navigator.share({ title: $("#product").value, text }); return; } catch {}
  }
  await navigator.clipboard.writeText(text);
  downloadBlob("sideclip-posting-pack.txt", "text/plain", text);
  toast("Full post caption copied and downloaded.");
});
$("#openMediaButton").addEventListener("click", () => showView("assets"));

async function boot() {
  $(".register-field").style.display = "none";
  const restored = restoreLocalDraft();
  await loadSession();
  if (!state.plan.length) {
    await generatePlan();
    openEditor(state.plan[0]);
    showView("brief");
  } else if (!restored && !state.projectId) {
    showView("brief");
  }
  if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => {});
}
boot();
